import Head from 'next/head';
import Link from "next/link";
import {Button} from "antd";


const Home = () => {

    return (
        <div>
            <Head>
                <title>Boiler-Nextjs-NextAuthJs</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <h1>Mehmet Halis Çiçek...</h1>
            <Link href={'/auth/signin'}> login </Link>
            <br/>
            <Link href={'/auth/signup'}>register</Link>
            <br/>
            <Button type={'primary'}>Hello</Button>

        </div>
    )
}
export default Home;
